[workspace]
resolver = "2"
members = [
    "xtask",
    "keyboard_mirror",
    "fake_sustain",
]


[workspace.dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "400eb3156f221073fbcaf95607b56842272d134b", features = ["assert_process_allocs"] }

